add missing translation strings
dumpus-app/dumpus-app pull request #237
Opened 2023-07-20 14:12 UTC by Androz2091

2023-07-20 15:14 UTC, florian-lefebvre commented
Ping me once you think it's ready for review 👍

2023-07-20 20:22 UTC, Androz2091 commented on src/app/[locale]/(app)/(nav)/(time-selector)/top/_components/TopSelector.tsx
> +    name: "guids",
there is an issue here, should be `guilds`

2023-07-20 20:23 UTC, Androz2091 commented on locales/en.json
> +"top"  : "top"  ,
`top` should be `Top`

2023-07-21 11:33 UTC, florian-lefebvre requested changes
Thanks for your work already! I've left quite some comments, feel free to ask anything

2023-07-21 11:33 UTC, florian-lefebvre commented on locales/en.json
> +        "gotTt" : "Got it!" ,
```suggestion
        "confirm" : "Got it!" ,
```

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/(top)/top/channels/details/_components/RelatedGuild.tsx
> +    <Section title="top.relatedGuild">
```suggestion
    <Section title={t("top.relatedGuild")}>
```

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/(top)/top/channels/details/_components/RelatedGuild.tsx
> +          description={`${formatNumber(messagesCount)} ${t("top.messageSent")}`}
Please refactor so that we pass the number to the translation

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/(top)/top/guilds/details/_components/Profile.tsx
> +          ? `${data.member_count} ${t("top.members")}`
refactor to pass number as a parameter of the `t` function

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/(top)/top/guilds/details/_components/Stats.tsx
> +      label: "top.totalMessageSent",
For all of the labels, call `t` after importing it and adding the "use client" directive

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/(top)/top/guilds/details/_components/TopChannels.tsx
> +    <Section title="top.topChannels">
```suggestion
    <Section title={t("top.topChannels")}>
```
Don't forget to import `t`

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/(top)/top/guilds/details/_components/TopUsedBots.tsx
> +          {bot.total_occurences} {t("top.commands")}
refactor to pass the number as an argument

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/(top)/top/guilds/details/_components/TopUsedBots.tsx
> +    <Section title="top.topUsedBots">
```suggestion
    <Section title={t("top.topUsedBots")}>
```
import `t`

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/_components/TimeSelector.tsx
> +            {t(`top.${time}`)}
Ignore the translation of time ranges for now

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/stats/_components/ExtraStats.tsx
> +        label="stats.notificationsClicked"
For all of the labels, call `t` after importing it and adding the "use client" directive

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/stats/_components/SendingTimes.tsx
> +      label: "overview.averageMessage",
For all of the labels, call `t` after importing it and adding the "use client" directive

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/stats/_components/ExtraStats.tsx
> -import {
Why deleting those lines, are they unused?

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/top/channels/_components/TopChannelsList.tsx
> +            ) } ${t("top.messageSent")}`}
refactor to pass data as parameters

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/top/dms/_components/TopDmsList.tsx
> +      description={formatNumber(dm.message_count) +  t('top.messageSent')}
refactor to pass data as parameter

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/(time-selector)/top/guilds/_components/TopGuildsList.tsx
> +      description={formatNumber(guild.message_count) + t("top.messageSent")}
refactor to pass data as parameter

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/_components/TopNav.tsx
> +import type { Link as LinkType, PageProps } from "~/types";
Looks like PageProps is not needed here. Please revert

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/overview/_components/SendingTimes.tsx
> +      label: "averageMessage",
For all of the labels, call `t` after importing it and adding the "use client" directive

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/(app)/(nav)/overview/_components/UsageStats.tsx
> +      label: "overview.messagesSent",
For all of the labels, call `t` after importing it and adding the "use client" directive

2023-07-21 11:33 UTC, florian-lefebvre commented on src/app/[locale]/onboarding/loading/_components/QueueDisplay.tsx
> +                    {t("onboarding.loading.queue.gotTt")}
```suggestion
                    {t("onboarding.loading.queue.confirm")}
```

2023-07-21 11:33 UTC, florian-lefebvre commented on src/components/Section.tsx
> +        <div className="text-lg font-bold text-white sm:text-2xl">{t(title)}</div>
I think it shouldn't be responsible for translating. Let's keep the logic outside of this component

2023-07-21 11:33 UTC, florian-lefebvre commented on src/components/data/AvatarCard.tsx
> +        {formatNumber(messages)} {t("overview.messages")}
refactor to pass data as parameter

2023-07-21 11:33 UTC, florian-lefebvre commented on src/components/data/StatCard.tsx
> +        <div className="text-sm text-gray-50 sm:text-lg">{t(label)}</div>
I think it shouldn't be responsible for translating. Let's keep the logic outside of this component

2023-07-21 11:33 UTC, florian-lefebvre commented on src/stores/config.ts
> +export const timeRanges = ["4Weeks", "6Months", "year", "lifetime"] as const;
leave it for now

2023-07-21 11:33 UTC, florian-lefebvre commented on src/types/index.ts
> +export type TopNavLinksNames  = "overview" |"top" | "stats"
Where is it used?

2023-07-25 14:48 UTC, closed without merging